### ISSUE TITLE
Accent Positioning: inverted breve 

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Asap#4]
@moyogo 
The accented chars with the inverted breve are misaligned. The purple outline is the current TTF.

![E inverted](https://user-images.githubusercontent.com/6576107/83585027-c61eeb00-a516-11ea-90d9-c779ab7a9f38.png)

**Comment by moyogo** [comment]
This was addressed in a72ba77 by decomposing scaled components. The inverted breve was a flipped breve and the flattenComponents filter was not handling it properly.
