### ISSUE TITLE
Some marks appear too light

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Asap#6]
Just inspected the lastest commit and found this.

![asap_marks](https://user-images.githubusercontent.com/7525512/98683699-4286e700-235d-11eb-9713-d43d88cd5e1f.gif)

cc @pichotta @moyogo

**Comment by m4rc1e** [comment]
This is happening on OSX 11.1 and it's happening to the Roman only.

**Comment by m4rc1e** [comment]
Also happens on OSX Safari 13.1

![asap2](https://user-images.githubusercontent.com/7525512/98808793-a4565800-2414-11eb-92e9-62c05604455e.gif)

**Comment by pichotta** [comment]
@moyogo 
It fixed the contour order of the inverted breves in the roman. Would you be able to test in the diff and OSX 11.1 and OSX Sarari 13.1?

**Comment by pichotta** [comment]
@m4rc1e 
Thank you for flagging the light /breveinvertedcomb and /breveinvertedcomb.case. 
The contour direction has been fixed for the inverted breves, in addition to a handful of other glyphs. The last commit also has a new build.
